using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace msentregadorescs.Migrations
{
    /// <inheritdoc />
    public partial class InitialCreate : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Usa IF NOT EXISTS para ser compatível com bancos onde o Prisma
            // já criou a tabela "entregadores" previamente.
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS entregadores (
                    id integer GENERATED BY DEFAULT AS IDENTITY,
                    nome character varying(100),
                    telefone character varying(20),
                    veiculo character varying(50),
                    CONSTRAINT entregadores_pkey PRIMARY KEY (id)
                );
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "entregadores");
        }
    }
}
